
spring:
    application:
      name: study-project
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3307/study-project?serverTimezone=Asia/Seoul
      username: root
      password: 1234
    jpa:
      open-in-view: true
      hibernate:
        ddl-auto: create
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      properties:
        hibernate.format_sql: true

server:
  port: 8090


